import { Inter } from "next/font/google";
import {
  // Nunito_Sans,
  Poppins,
  Manrope,
  DM_Sans,
  League_Script,
  Oswald,
} from "next/font/google";
import "./globals.css";
// import Navbar from "@/ui/Navbar";
// import Footer from "@/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const nunito_sans_init = Nunito_Sans({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-nunito_sans",
//   weight: ["400", "600", "700"],
// });
export const poppins_init = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "600", "700"],
});
export const manrope_init = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
  weight: ["400", "600", "700", "800"],
});
export const dm_sans_init = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700", "800"],
});
export const league_script = League_Script({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-league-script",
  weight: ["400"],
});
export const oswald_init = Oswald({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald",
  weight: ["400", "600", "700"],
});
// ${nunito_sans_init.variable}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}
        ${poppins_init.variable} ${manrope_init.variable}
        ${dm_sans_init.variable} ${league_script.variable} ${oswald_init.variable}`}
      >
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
